#!/bin/sh
./tst -s demos/demo0.pl -i "1\n2\n3"
./tst -s demos/demo1.pl -a "hello 10"
./tst -s demos/demo2.pl -a "12"
./tst -s demos/demo2.pl -a "25"
./tst -s demos/demo2.pl -a "22"
./tst -s demos/demo2.pl -a "-4"
./tst -s demos/demo2.pl -a "33"
